export const GET_SOURCES_OPTIONS = 'GET_SOURCES_OPTIONS';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_SORTBY_OPTIONS = 'GET_SORTBY_OPTIONS';
export const GET_PERIOD_OPTIONS = 'GET_PERIOD_OPTIONS';
export const GET_MORE_ARTICLES = 'GET_MORE_ARTICLES';